### ISSUE TITLE
Object Variable Or With Block Variable Not Set for Function 3S and Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jtalati** [NYCPlanning/WebGbat#4]
Steps to recreate are in the pictures below:
1. ![functionselect](https://user-images.githubusercontent.com/24463592/36327643-28a72932-132d-11e8-82b7-c643f464a625.jpg)
2. ![excelinputsample](https://user-images.githubusercontent.com/24463592/36327654-35397ea2-132d-11e8-9509-20fe9399c43c.jpg)
3. ![err2](https://user-images.githubusercontent.com/24463592/36327700-65062d10-132d-11e8-9cc4-072ec6daa031.jpg)
4. ![err1](https://user-images.githubusercontent.com/24463592/36327701-6510e1c4-132d-11e8-9ab6-9d60d41043f2.jpg)
5. ![outputselectpage](https://user-images.githubusercontent.com/24463592/36327702-651eac28-132d-11e8-8f67-294af23dc395.jpg)

**Comment by ns5001** [comment]
Fixed
