### ISSUE TITLE
Default WebGBAT Max Rejects? 

### ISSUE THREAD

**Issue by jtalati** [NYCPlanning/WebGbat#8]
From My understanding we dont have a default reject stop policy!

Desktop Edition and Mainframe Edition of GBAT allow a user to request that GBAT stop processing after a cerain number of input records have been rejected by Geosupport (GRC > 1).  The default is 200 records.  

It can be useful when the user is processing a large spreadsheet.

Is there an option like that available in WebGBAT?

**Comment by ns5001** [comment]
No we don't have that feature. Would they like us to add it?

**Comment by jtalati** [comment]
This is a question for @nileshpalve. We already have an error tab. if there are many errors in the excel spreadsheet the user is limited to one option which is to use another spreadsheet with less geocoded errors.
